name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge, defaults
        use-only-tar-bz2: true
        auto-update-conda: true
        auto-activate-base: true

    - name: Create Conda environment
      run: conda create -n myenv python=3.9

    - name: Activate Conda environment
      run: conda activate myenv

    - name: Check for Cython installation
      run: |
        conda list | grep cython || conda install -y cython

    - name: Compile Cython/C code
      run: python setup.py build_ext --inplace install
